name: contribute
on:
  schedule:
    - cron: "0 1 * * *"
  workdispach:
jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Auto always green
        run: |
          git config --local user.email "moesama-zzt@163.com" # 此处替换成你GitHub的邮箱地址 
          git config --local user.name "moesama-zzt" # 此处替换成你GitHub的账号昵称
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "no bugs,no bugs!"
          git push
