# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake
        id: snake-gif
        uses: Platane/snk@
        with:
          github_user_name: ${{ github.repository_owner }}
          gif_out_path: ./assets/github-contribution-grid-snake.gif
          svg_out_path: ./assets/github-contribution-grid-snake.svg

      - name: Set Gif Path
        run: echo "GIF_PATH=./assets/github-contribution-grid-snake.gif" >> $GITHUB_ENV

      - name: Set Svg Path
        run: echo "SVG_PATH=./assets/github-contribution-grid-snake.svg" >> $GITHUB_ENV

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v8
        env:
          ACCESS_TOKEN: ${{ secrets.WRITE_ACCESS_TOKEN }}
          GIF_PATH: ${{ env.GIF_PATH }}
          SVG_PATH: ${{ env.SVG_PATH }}
        with:
          default_author: github_actor
          message: Generate Contribution Snake
          files: ${{ env.GIF_PATH }} ${{ env.SVG_PATH }}
