# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          gif_out_path: ./assets/github-contribution-grid-snake.gif
          svg_out_path: ./assets/github-contribution-grid-snake.svg

      - name: Write Gif Path to Environment File
        run: echo "SNAKE_GIF_PATH=./assets/github-contribution-grid-snake.gif" >> $GITHUB_ENV

      - name: Write Svg Path to Environment File
        run: echo "SNAKE_SVG_PATH=./assets/github-contribution-grid-snake.svg" >> $GITHUB_ENV

      - name: Commit Changes
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add ${{ env.SNAKE_GIF_PATH }} ${{ env.SNAKE_SVG_PATH }}
          git commit -m "Generate Contribution Snake"
          git push
